CREATE DATABASE EV_MARKET;
SHOW DATABASES;
USE EV_MARKET;
SHOW TABLES;
SELECT*
FROM EV_DATA;

SELECT COUNT(*) AS TOTAL_VEHICLES
FROM EV_DATA;

SELECT `Electric Vehicle Type`, COUNT(*) AS total
FROM ev_data
GROUP BY `Electric Vehicle Type`
ORDER BY total DESC;


SELECT Make, COUNT(*) AS TOTAL
FROM EV_DATA
GROUP BY MAKE 
ORDER BY TOTAL DESC
LIMIT 10;

SELECT MAKE , ROUND(AVG(`ELECTRIC RANGE`),2) AS AVG_RANGE
FROM EV_DATA
WHERE `ELECTRIC RANGE`>0
GROUP BY MAKE 
ORDER BY AVG_RANGE DESC
LIMIT 10;

SELECT `MODEL YEAR`, COUNT(*) AS TOTAL
FROM EV_DATA
GROUP BY `MODEL YEAR`
ORDER BY `MODEL YEAR`;

SELECT CITY, COUNT(*) AS TOTAL
FROM EV_DATA
GROUP BY CITY
ORDER BY TOTAL DESC
LIMIT 5;

SELECT `MODEL YEAR`, ROUND(AVG(`ELECTRIC RANGE`), 2) AS AVG_RANGE_PER_YEAR
FROM EV_DATA
WHERE `ELECTRIC RANGE`>0
GROUP BY `MODEL YEAR`
ORDER BY `MODEL YEAR`;

SELECT COUNTY, COUNT(*) AS TOTAL_VEHICLES
FROM EV_DATA
GROUP BY COUNTY
ORDER BY TOTAL_VEHICLES DESC
LIMIT 10;


SELECT*
FROM EV_DATA;